export const products = [
  {
    id: 1,
    name: 'Flower Yum',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/flower_yum.png',
  },
  {
    id: 2,
    name: 'Flowers in Vase on Pink',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/flowers_in_vase_on_pink.png',
  },
  {
    id: 3,
    name: 'Lapland Christmas',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/lapland_christmas.png',
    thumbnail: '/assets/Store/Prints/Thumbnails/lapland_christmas.png',
  },
  {
    id: 4,
    name: 'Lion Flower',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/lion_flower.png',
  },
  {
    id: 5,
    name: 'Nessie Flowers on Black',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/nessie_flowers_on_black.png',
    thumbnail: '/assets/Store/Prints/Thumbnails/nessie_flowers_on_black.png',
  },
  {
    id: 6,
    name: 'Nessie Flowers on White',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/nessie_flowers_on_white.png',
    thumbnail: '/assets/Store/Prints/Thumbnails/nessie_flowers_on_white.png',
  },
  {
    id: 7,
    name: 'New Flowers On Black',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/new_flowers_on_black.png',
    thumbnail: '/assets/Store/Prints/Thumbnails/new_flowers_on_black.png',
  },
  {
    id: 8,
    name: 'Newest Flowers',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/newest_flowers.png',
    thumbnail: '/assets/Store/Prints/Thumbnails/newest_flowers.png',
  },
  {
    id: 9,
    name: 'Otters',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/otters.png',
    thumbnail: '/assets/Store/Prints/Thumbnails/otters.png',
  },
  {
    id: 10,
    name: 'Reindeer Star',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/reindeer_star.png',
  },
  {
    id: 11,
    name: 'Yellow Flower on Black',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/yellow_flower_on_black.png',
    thumbnail: '/assets/Store/Prints/Thumbnails/yellow_flower_on_black.png',
  },
  {
    id: 12,
    name: 'Yellow Flower',
    type: 'Print A5 on 240 gsm paper',
    price: 15,
    image: '/assets/Store/Prints/yellow_flower.png',
    thumbnail: '/assets/Store/Prints/Thumbnails/yellow_flower.png',
  },
  {
    id: 13,
    name: 'Bok Choy',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/bok_choy.jpg',
  },
  {
    id: 14,
    name: 'Buttercup',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/buttercup.jpg',
  },
  {
    id: 15,
    name: 'Cry',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/cry.jpg',
  },
  {
    id: 16,
    name: 'Emotion',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/emotion.jpg',
  },
  {
    id: 17,
    name: 'Fish',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/fish.jpg',
  },
  {
    id: 18,
    name: 'Flowers in Vase',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/flowers_in_vase.jpg',
  },
  {
    id: 19,
    name: 'Flower Yum',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/flower_yum.jpg',
    thumbnail: '/assets/Store/Prints/Thumbnails/flower_yum.png',
  },
  {
    id: 20,
    name: 'Happy Bday',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/happy_bday.jpg',
  },
  {
    id: 21,
    name: 'Heart',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/heart.jpg',
  },
  {
    id: 22,
    name: 'Insect',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/insect.jpg',
  },
  {
    id: 23,
    name: 'It Is Ok',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/it_is_ok.jpg',
  },
  {
    id: 24,
    name: 'Nessie Flowers',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/nessie_flowers.jpg',
  },
  {
    id: 25,
    name: 'Pigeon',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/pigeon.jpg',
  },
  {
    id: 26,
    name: 'Fawn',
    type: 'Premium Vinyl Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/fawn.jpg',
  },
  {
    id: 27,
    name: 'Rosehips',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/rosehips.jpg',
  },
  {
    id: 28,
    name: 'Rosehips Silver',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/rosehips_silver.jpg',
  },
  {
    id: 29,
    name: 'Sardines',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/sardines.jpg',
  },
  {
    id: 30,
    name: 'Tulip',
    type: 'Premium Holographic Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/tulip.jpg',
  },
  {
    id: 31,
    name: 'Yellow Flower',
    type: 'Premium Vinyl Sticker 7cm',
    price: 3,
    image: '/assets/Store/Stickers/yellow_flower.jpg',
  },
];
