export const products = [
  {
    id: 1,
    name: 'Antirrhinum abstract on red',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/Antirrhinum_abstract_on_red.jpg',
  },
  {
    id: 2,
    name: 'Flower Yum',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/flower_yum.png',
  },
  {
    id: 3,
    name: 'Flowers in Vase on Pink',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/flowers_in_vase_on_pink.png',
  },
  {
    id: 4,
    name: 'Nessie Flowers on Black',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/nessie_flowers_on_black.png',
  },
  {
    id: 5,
    name: 'Nessie Flowers on White',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/nessie_flowers_on_white.png',
  },
  {
    id: 6,
    name: 'Reindeer Star',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/reindeer_star.png',
  },
  {
    id: 7,
    name: 'Winter Flowers On Black',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/winter_flowers_on_black.png',
  },
  {
    id: 8,
    name: 'Yellow Flower on Black',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/yellow_flower_on_black.png',
  },
  {
    id: 9,
    name: 'Yellow Flower',
    type: 'Print A4 on 300gsm paper',
    price: 25,
    image: '/assets/Store/yellow_flower.png',
  },
];
